### ISSUE TITLE
snpeff docker image not found

### ISSUE THREAD

**Issue by slagelwa** [h3abionet/h3agatk#1]
Was trying to run the workflow and encountered the following error:

```
['docker', 'pull', 'quay.io/snpeff:4.3']
Error response from daemon: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\n"
Got workflow error
Traceback (most recent call last):
  File "/home/jslagel/.local/lib/python2.7/site-packages/cwltool/main.py", line 224, in single_job_executor
    r.run(**kwargs)
  File "/home/jslagel/.local/lib/python2.7/site-packages/cwltool/job.py", line 140, in run
    img_id = docker.get_from_requirements(docker_req, docker_is_req, pull_image)
  File "/home/jslagel/.local/lib/python2.7/site-packages/cwltool/docker.py", line 105, in get_from_requirements
    if get_image(r, pull_image, dry_run):
  File "/home/jslagel/.local/lib/python2.7/site-packages/cwltool/docker.py", line 43, in get_image
    subprocess.check_call(cmd, stdout=sys.stderr)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['docker', 'pull', 'quay.io/snpeff:4.3']' returned non-zero exit status 1
Workflow error, try again with --debug for more information:
Command '['docker', 'pull', 'quay.io/snpeff:4.3']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/jslagel/.local/lib/python2.7/site-packages/cwltool/main.py", line 728, in main
    **vars(args))
  File "/home/jslagel/.local/lib/python2.7/site-packages/cwltool/main.py", line 232, in single_job_executor
    raise WorkflowException(Text(e))
WorkflowException: Command '['docker', 'pull', 'quay.io/snpeff:4.3']' returned non-zero exit status 1
```

Querying quay.io, I wasn't able to find the docker image referred to by the cwl recipe.  I replaced the reference in snpeff.cwl to use biocontainers/snpeff:4.3--2 for the time being in our workflow.

(FYI @smrgit)

**Comment by pvanheus** [comment]
Thanks I changed to the quay.io one in PR #3. This issue should now be resolved, please test @slagelwa
